helloworld/config/routes.rb
Helloworld::Application.routes.draw do
  resources :hellos

end

helloworld/app/models/hello.rb
class Hello < ActiveRecord::Base
  attr_accessible :color, :from, :message
  validates :color, :format => { :with => /^#[0-9A-Fa-f]{6}$/,  :message => "Only HTML-Color codes allowed!" }
end

helloworld/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

helloworld/app/controllers/hellos_controller.rb
class HellosController < ApplicationController
  # GET /hellos
  # GET /hellos.json
  def index
    @hellos = Hello.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hellos }
    end
  end

  # GET /hellos/1
  # GET /hellos/1.json
  def show
    @hello = Hello.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hello }
    end
  end

  # GET /hellos/new
  # GET /hellos/new.json
  def new
    @hello = Hello.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hello }
    end
  end

  # GET /hellos/1/edit
  def edit
    @hello = Hello.find(params[:id])
  end

  # POST /hellos
  # POST /hellos.json
  def create
    @hello = Hello.new(params[:hello])

    respond_to do |format|
      if @hello.save
        format.html { redirect_to @hello, notice: 'Hello was successfully created.' }
        format.json { render json: @hello, status: :created, location: @hello }
      else
        format.html { render action: "new" }
        format.json { render json: @hello.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hellos/1
  # PUT /hellos/1.json
  def update
    @hello = Hello.find(params[:id])

    respond_to do |format|
      if @hello.update_attributes(params[:hello])
        format.html { redirect_to @hello, notice: 'Hello was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hello.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hellos/1
  # DELETE /hellos/1.json
  def destroy
    @hello = Hello.find(params[:id])
    @hello.destroy

    respond_to do |format|
      format.html { redirect_to hellos_url }
      format.json { head :no_content }
    end
  end
end

helloworld/app/helpers/application_helper.rb
module ApplicationHelper
end

helloworld/app/helpers/hellos_helper.rb
module HellosHelper
end

helloworld/app/views/hellos/_form.html.erb
<%= form_for(@hello) do |f| %>
  <% if @hello.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hello.errors.count, "error") %> prohibited this hello from being saved:</h2>

      <ul>
      <% @hello.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :from %><br />
    <%= f.text_field :from %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :color %><br />
    <%= f.text_field :color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

helloworld/app/views/hellos/edit.html.erb
<h1>Editing hello</h1>

<%= render 'form' %>

<%= link_to 'Show', @hello %> |
<%= link_to 'Back', hellos_path %>

helloworld/app/views/hellos/index.html.erb
<style>
    div.message{
        display: inline-block;
        border: 2px dashed #cccccc;
        padding: 1em;
        box-shadow: 0 0 10px 10px #eeeeee inset;
    }
    div.message h2{
        margin-top: 0;
    }
    div.message blockquote{
        background-color: #ffffff;
        padding: 5px;
    }
    div.edit ul li{
        display: inline-block;
    }
    div.edit ul{
        list-style-type: none;
        margin: 0;
        padding: 0;
        float: right;
    }
</style>
<h1>Listing hellos</h1>
<%= link_to 'New Hello', new_hello_path %>
<hr>
<% @hellos.each do |hello| %>
    <div class="message">
      <h2>From: <span class="author"><%= hello.from %></span></h2>
      <blockquote style="box-shadow: 0 0 10px 10px <%= hello.color %>;"><%= hello.message[0..99] %><%= link_to '...', hello %></blockquote>
      <div class="edit"><ul>
        <li><%= link_to 'Edit', edit_hello_path(hello) %></li>
        <li><%= link_to 'Destroy', hello, method: :delete, data: { confirm: 'Are you sure?' } %></li>
      </ul></div>
    </div>
<% end %>

helloworld/app/views/hellos/new.html.erb
<h1>New hello</h1>

<%= render 'form' %>

<%= link_to 'Back', hellos_path %>

helloworld/app/views/hellos/show.html.erb
<p id="notice"><%= notice %></p>

<div class="message">
  <p><span class="author"><%= @hello.from %></span> says:</p>
  <blockquote class="text" style="color: <%= @hello.color %>"><%= @hello.message %></blockquote>
</div>

<%= link_to 'Edit', edit_hello_path(@hello) %> |
<%= link_to 'Back', hellos_path %> |
<%= link_to 'All Messages', hellos_url %>

helloworld/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Helloworld</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>